/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    NotificationDropdown: typeof import('./components/common/NotificationDropdown.vue')['default']
    ProjectForm: typeof import('./components/projects/ProjectForm.vue')['default']
    ReportFilterPanel: typeof import('./components/reports/ReportFilterPanel.vue')['default']
    ReportSummaryCard: typeof import('./components/reports/ReportSummaryCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./components/tasks/TaskCard.vue')['default']
    TaskForm: typeof import('./components/tasks/TaskForm.vue')['default']
    TimeRequestApprovalModal: typeof import('./components/time-requests/TimeRequestApprovalModal.vue')['default']
    TimeRequestForm: typeof import('./components/time-requests/TimeRequestForm.vue')['default']
    TimesheetForm: typeof import('./components/timesheets/TimesheetForm.vue')['default']
    UserForm: typeof import('./components/users/UserForm.vue')['default']
    WorkHoursCalculator: typeof import('./components/timesheets/WorkHoursCalculator.vue')['default']
  }
}
